name: flutter_invoice_app
description: A comprehensive GST invoice management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.5
  intl: 0.20.2
  
  # State management
  provider: ^6.0.5
  
  # Navigation
  go_router: ^10.1.2
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Database
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Storage and files
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.1
  
  # Device info and permissions
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.5
  
  # Firebase - Stable older versions
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.2.6
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  
  # UI and styling
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  
  # PDF and documents
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # File handling
  file_picker: ^5.5.0
  share_plus: ^7.1.0
  
  # Utilities
  uuid: ^3.0.7
  crypto: ^3.0.3
  
  # Logging and debugging
  logger: ^1.4.0
  
  # Charts and graphs
  fl_chart: ^0.63.0
  
  # Date and time
  table_calendar: ^3.0.9
  
  # Connectivity
  connectivity_plus: ^4.0.2
  
  # Image handling
  image: ^4.0.17
  image_picker: ^1.0.4
  
  # QR codes
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Excel files
  excel: ^2.1.0
  
  # CSV files
  csv: ^5.0.2
  
  # Equatable for state management
  equatable: ^2.0.5
  
  # Payment processing
  flutter_stripe: ^9.4.0
  
  # URL launcher
  url_launcher: ^6.1.14
  
  # Biometric authentication
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sample_data/
    - assets/config/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
